# Generated by Django 3.2.9 on 2021-11-29 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выписки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('payed', models.IntegerField(verbose_name='Оплачено')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('М', 'Male'), ('Ж', 'Female')], max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус Клиента',
                'verbose_name_plural': 'Статусы Клиентов',
                'db_table': 'ClientStatus',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Наименование')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Курс')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('М', 'Male'), ('Ж', 'Female')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='FeedingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип Питания',
                'verbose_name_plural': 'Типы Питания',
                'db_table': 'FeedingType',
            },
        ),
        migrations.CreateModel(
            name='HotelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип Отеля',
                'verbose_name_plural': 'Типы Отелей',
                'db_table': 'HotelType',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=45, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=45, null=True, verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='PreliminaryAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заключения')),
                ('trip_start', models.DateField(verbose_name='Дата начала поездки')),
                ('trip_end', models.DateField(verbose_name='Дата конца поездки')),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.DO_NOTHING, to='db.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.employee', verbose_name='Агент')),
                ('organization', models.ForeignKey(db_column='organization', on_delete=django.db.models.deletion.CASCADE, to='db.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Предварительное Соглашение',
                'verbose_name_plural': 'Предварительные Соглашения',
                'db_table': 'PreliminaryAgreement',
            },
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус Процесса',
                'verbose_name_plural': 'Статусы Процесса',
                'db_table': 'ProcessStatus',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип Комнаты',
                'verbose_name_plural': 'Типы Комнат',
                'db_table': 'RoomType',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('group', models.OneToOneField(db_column='group', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, to='db.city', verbose_name='Город')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='db.hoteltype', verbose_name='Тип отеля')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'db_table': 'Hotel',
                'unique_together': {('id', 'city')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(db_column='organization', on_delete=django.db.models.deletion.CASCADE, to='db.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(db_column='position', on_delete=django.db.models.deletion.CASCADE, to='db.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('currency', models.ForeignKey(db_column='currency', on_delete=django.db.models.deletion.CASCADE, to='db.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'db_table': 'Contract',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='db.clientstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='db.country', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='TourHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Порядок')),
                ('start_date', models.DateTimeField(verbose_name='Дата заселения')),
                ('end_date', models.DateTimeField(verbose_name='Дата выселения')),
                ('agreement', models.ForeignKey(db_column='agreement', on_delete=django.db.models.deletion.CASCADE, to='db.preliminaryagreement', verbose_name='Предварительно соглашение')),
                ('feeding_type', models.ForeignKey(db_column='feeding_type', on_delete=django.db.models.deletion.CASCADE, to='db.feedingtype', verbose_name='Тип питания')),
                ('hotel', models.ForeignKey(db_column='hotel', on_delete=django.db.models.deletion.CASCADE, to='db.hotel', verbose_name='Отель')),
                ('room_type', models.ForeignKey(db_column='room_type', on_delete=django.db.models.deletion.CASCADE, to='db.roomtype', verbose_name='Тип комнаты')),
            ],
            options={
                'db_table': 'TourHotel',
                'unique_together': {('id', 'agreement', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='InternationalPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Серия')),
                ('number', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Номер')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=45, verbose_name='Место рождения')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(verbose_name='Дата окончания срока действия')),
                ('authority', models.CharField(max_length=45, verbose_name='Орган, выдавший документ')),
                ('client', models.OneToOneField(db_column='client', on_delete=django.db.models.deletion.CASCADE, to='db.client', verbose_name='Клиент')),
            ],
            options={
                'db_table': 'InternationalPassport',
                'unique_together': {('id', 'client')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('id', 'position', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('id', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('id', 'country')},
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('agreement', models.ForeignKey(db_column='agreement', on_delete=django.db.models.deletion.CASCADE, to='db.preliminaryagreement', verbose_name='Предварительное соглашение')),
                ('bill', models.ForeignKey(blank=True, db_column='bill', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.bill', verbose_name='Чек')),
                ('contract', models.ForeignKey(blank=True, db_column='contract', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.contract', verbose_name='Договор')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='db.processstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бизнес процесс',
                'verbose_name_plural': 'Бизнес процессы',
                'db_table': 'BusinessProcess',
                'unique_together': {('id', 'agreement', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('contract', models.OneToOneField(db_column='contract', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.contract', verbose_name='Договор')),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.DO_NOTHING, to='db.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
                'db_table': 'Tourist',
                'unique_together': {('contract', 'client')},
            },
        ),
    ]
