# Generated by Django 3.2.9 on 2021-11-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Фото'),
        ),
    ]
