-- MySQL Script generated by MySQL Workbench
-- Thu 18 Nov 2021 09:34:45 PM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TravelerDream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TravelerDream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TravelerDream` DEFAULT CHARACTER SET utf8 ;
USE `TravelerDream` ;

-- -----------------------------------------------------
-- Table `TravelerDream`.`Position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` INT NOT NULL,
  `organization` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `sex` ENUM('М', 'Ж') NOT NULL,
  `birth_date` DATE NOT NULL,
  `photo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `position`, `organization`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Employee_Position_idx` (`position` ASC) VISIBLE,
  INDEX `fk_Employee_Organization1_idx` (`organization` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Position`
    FOREIGN KEY (`position`)
    REFERENCES `TravelerDream`.`Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Organization1`
    FOREIGN KEY (`organization`)
    REFERENCES `TravelerDream`.`Organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`ClientStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`ClientStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `sex` ENUM('М', 'Ж') NOT NULL,
  `birth_date` DATE NOT NULL,
  `birth_place` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `status`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Client_Status1_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Status1`
    FOREIGN KEY (`status`)
    REFERENCES `TravelerDream`.`ClientStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`InternationalPassport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`InternationalPassport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client` INT NOT NULL,
  `type` VARCHAR(3) NOT NULL,
  `state` VARCHAR(3) NOT NULL,
  `series` DECIMAL(2,0) UNSIGNED NOT NULL,
  `number` DECIMAL(7,0) UNSIGNED NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `given_name` VARCHAR(45) NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` ENUM('М', 'Ж') NOT NULL,
  `birth_place` VARCHAR(45) NOT NULL,
  `issue_date` DATE NOT NULL,
  `expiry_date` DATE NOT NULL,
  `authority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `client`),
  INDEX `fk_InternationalPassport_Client1_idx` (`client` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `client_UNIQUE` (`client` ASC) VISIBLE,
  CONSTRAINT `fk_InternationalPassport_Client1`
    FOREIGN KEY (`client`)
    REFERENCES `TravelerDream`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Passport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Passport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client` INT NOT NULL,
  `series` DECIMAL(4,0) UNSIGNED NOT NULL,
  `number` DECIMAL(6,0) UNSIGNED NOT NULL,
  `authority` VARCHAR(255) NOT NULL,
  `issue_date` DATE NOT NULL,
  `authority_code` DECIMAL(6,0) UNSIGNED NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `sex` ENUM('М', 'Ж') NOT NULL,
  `birth_date` DATE NOT NULL,
  `birth_place` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `client`),
  INDEX `fk_Passport_Client1_idx` (`client` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `client_UNIQUE` (`client` ASC) VISIBLE,
  CONSTRAINT `fk_Passport_Client1`
    FOREIGN KEY (`client`)
    REFERENCES `TravelerDream`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`BirthCertificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`BirthCertificate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client` INT NOT NULL,
  `series` VARCHAR(5) NOT NULL,
  `number` DECIMAL(6,0) UNSIGNED NOT NULL,
  `issue_date` DATE NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `birth_date` DATE NOT NULL,
  `birth_place` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `client`),
  INDEX `fk_BirthCertificate_Client1_idx` (`client` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `client_UNIQUE` (`client` ASC) VISIBLE,
  CONSTRAINT `fk_BirthCertificate_Client1`
    FOREIGN KEY (`client`)
    REFERENCES `TravelerDream`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`City` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `country`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_City_Country1_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`country`)
    REFERENCES `TravelerDream`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`HotelType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`HotelType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` INT NOT NULL,
  `type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `city`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Hotel_City1_idx` (`city` ASC) VISIBLE,
  INDEX `fk_Hotel_HotelType1_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_City1`
    FOREIGN KEY (`city`)
    REFERENCES `TravelerDream`.`City` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_HotelType1`
    FOREIGN KEY (`type`)
    REFERENCES `TravelerDream`.`HotelType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`PreliminaryAgreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`PreliminaryAgreement` (
  `id` INT NOT NULL,
  `organization` INT NOT NULL,
  `employee` INT NULL,
  `client` INT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `trip_start` DATE NOT NULL,
  `trip_end` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PreliminaryAgreement_Organization1_idx` (`organization` ASC) VISIBLE,
  INDEX `fk_PreliminaryAgreement_Employee1_idx` (`employee` ASC) VISIBLE,
  INDEX `fk_PreliminaryAgreement_Client1_idx` (`client` ASC) VISIBLE,
  CONSTRAINT `fk_PreliminaryAgreement_Organization1`
    FOREIGN KEY (`organization`)
    REFERENCES `TravelerDream`.`Organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PreliminaryAgreement_Employee1`
    FOREIGN KEY (`employee`)
    REFERENCES `TravelerDream`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PreliminaryAgreement_Client1`
    FOREIGN KEY (`client`)
    REFERENCES `TravelerDream`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`RoomType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`RoomType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`FeedingType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`FeedingType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`TourHotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`TourHotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agreement` INT NOT NULL,
  `hotel` INT NOT NULL,
  `room_type` INT NOT NULL,
  `feeding_type` INT NOT NULL,
  `order` DECIMAL(2,0) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `agreement`, `hotel`),
  INDEX `fk_TourHotel_PreliminaryAgreement1_idx` (`agreement` ASC) VISIBLE,
  INDEX `fk_TourHotel_Hotel1_idx` (`hotel` ASC) VISIBLE,
  UNIQUE INDEX `TourHotelcol_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_TourHotel_RoomType1_idx` (`room_type` ASC) VISIBLE,
  INDEX `fk_TourHotel_FeedingType1_idx` (`feeding_type` ASC) VISIBLE,
  CONSTRAINT `fk_TourHotel_PreliminaryAgreement1`
    FOREIGN KEY (`agreement`)
    REFERENCES `TravelerDream`.`PreliminaryAgreement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TourHotel_Hotel1`
    FOREIGN KEY (`hotel`)
    REFERENCES `TravelerDream`.`Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TourHotel_RoomType1`
    FOREIGN KEY (`room_type`)
    REFERENCES `TravelerDream`.`RoomType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TourHotel_FeedingType1`
    FOREIGN KEY (`feeding_type`)
    REFERENCES `TravelerDream`.`FeedingType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Currency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  `rate` DECIMAL(5,2) NOT NULL,
  `update_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency` INT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `cost` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Contract_Currency1_idx` (`currency` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Currency1`
    FOREIGN KEY (`currency`)
    REFERENCES `TravelerDream`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Bill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATETIME NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `payed` TINYINT NOT NULL DEFAULT 0,
  `payment_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`ProcessStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`ProcessStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`BusinessProcess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`BusinessProcess` (
  `id` INT NOT NULL,
  `agreement` INT NOT NULL,
  `status` INT NOT NULL,
  `contract` INT NULL,
  `bill` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `agreement`, `status`),
  INDEX `fk_BusinessProcess_PreliminaryAgreement1_idx` (`agreement` ASC) VISIBLE,
  INDEX `fk_BusinessProcess_Contract1_idx` (`contract` ASC) VISIBLE,
  INDEX `fk_BusinessProcess_Bill1_idx` (`bill` ASC) VISIBLE,
  INDEX `fk_BusinessProcess_ProcessStatus1_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_BusinessProcess_PreliminaryAgreement1`
    FOREIGN KEY (`agreement`)
    REFERENCES `TravelerDream`.`PreliminaryAgreement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BusinessProcess_Contract1`
    FOREIGN KEY (`contract`)
    REFERENCES `TravelerDream`.`Contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BusinessProcess_Bill1`
    FOREIGN KEY (`bill`)
    REFERENCES `TravelerDream`.`Bill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BusinessProcess_ProcessStatus1`
    FOREIGN KEY (`status`)
    REFERENCES `TravelerDream`.`ProcessStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TravelerDream`.`Tourist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TravelerDream`.`Tourist` (
  `contract` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`contract`, `client`),
  INDEX `fk_Tourist_Client1_idx` (`client` ASC) VISIBLE,
  CONSTRAINT `fk_Tourist_Contract1`
    FOREIGN KEY (`contract`)
    REFERENCES `TravelerDream`.`Contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tourist_Client1`
    FOREIGN KEY (`client`)
    REFERENCES `TravelerDream`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
